/* eslint-disable @typescript-eslint/no-explicit-any */
import fs from "fs";
import path from "path";
import PDFDocument from "pdfkit";
import * as XLSX from "xlsx";

/**
 * ExportService - Handles PDF, Excel, and CSV export functionality
 */
export class ExportService {
  static readonly EXPORTS_DIR = path.join(process.cwd(), "exports", "reports");

  /**
   * Ensure exports directory exists
   */
  static ensureExportsDir(): void {
    if (!fs.existsSync(this.EXPORTS_DIR)) {
      fs.mkdirSync(this.EXPORTS_DIR, { recursive: true });
    }
  }

  /**
   * Generate unique filename
   */
  static generateFilename(reportType: string, format: "pdf" | "xlsx" | "csv"): string {
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-").split("T")[0];
    const random = Math.random().toString(36).substring(7);
    return `${timestamp}_${reportType}_${random}.${format}`;
  }

  /**
   * Export data to PDF format
   */
  static async exportToPdf(
    reportType: string,
    reportData: any[],
    filters: Record<string, any>,
    logoUrl?: string
  ): Promise<{ filePath: string; filename: string }> {
    this.ensureExportsDir();

    const filename = this.generateFilename(reportType, "pdf");
    const filePath = path.join(this.EXPORTS_DIR, filename);

    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 40 });
        const stream = fs.createWriteStream(filePath);

        doc.pipe(stream);

        // Header with logo (if provided)
        if (logoUrl) {
          try {
            doc.image(logoUrl, 40, 30, { fit: [100, 40], align: "center" });
            doc.moveDown(0.5);
          } catch (e) {
            // Logo loading failed, continue without it
          }
        }

        // Title
        doc.fontSize(20).font("Helvetica-Bold").text(`${reportType.toUpperCase()} Report`, { align: "center" });
        doc.moveDown(0.5);

        // Meta information
        doc.fontSize(10).font("Helvetica").text(`Generated: ${new Date().toUTCString()}`, { align: "center" });
        doc.moveDown(1);

        // Filters applied
        doc.fontSize(11).font("Helvetica-Bold").text("Filters Applied:", { underline: true });
        doc.fontSize(9).font("Helvetica");
        Object.entries(filters).forEach(([key, value]) => {
          if (value !== undefined && value !== null) {
            doc.text(`${key}: ${value}`);
          }
        });
        doc.moveDown(1);

        // Table headers and data
        if (reportData.length > 0) {
          const headers = Object.keys(reportData[0]);
          const columnWidths = this.calculateColumnWidths(headers, reportData);

          // Draw table header
          doc.fontSize(9).font("Helvetica-Bold").fillColor("white");
          let x = 40;
          headers.forEach((header, i) => {
            doc.rect(x, doc.y, columnWidths[i], 20).fill("#2c3e50");
            doc.fillColor("white")
              .text(header, x + 5, doc.y + 5, { width: columnWidths[i] - 10, height: 10 })
              .moveDown(0);
            x += columnWidths[i];
          });

          // Draw table rows
          doc.fillColor("black").font("Helvetica");
          reportData.slice(0, 50).forEach((row, rowIndex) => {
            x = 40;
            const bgColor = rowIndex % 2 === 0 ? "#f5f5f5" : "white";
            doc.fillColor(bgColor);

            headers.forEach((header, i) => {
              const cellHeight = 20;
              doc.rect(x, doc.y, columnWidths[i], cellHeight).fill(bgColor);
              doc.fillColor("black")
                .fontSize(8)
                .text(String(row[header] || ""), x + 5, doc.y + 5, {
                  width: columnWidths[i] - 10,
                  height: cellHeight - 10,
                  ellipsis: true,
                })
                .moveDown(0);
              x += columnWidths[i];
            });

            doc.moveDown(1);

            // Add new page if needed
            if (doc.y > 700) {
              doc.addPage();
            }
          });
        }

        // Footer
        doc.fontSize(8).fillColor("gray").text(`Total records: ${reportData.length}`, { align: "center" });
        doc.text("Generated by SMT Verification System", { align: "center" });

        doc.end();

        stream.on("finish", () => {
          resolve({ filePath, filename });
        });

        stream.on("error", (err) => {
          reject(err);
        });
      } catch (error) {
        reject(error);
      }
    });
  }

  /**
   * Export data to Excel format
   */
  static async exportToExcel(
    reportType: string,
    reportData: any[],
    filters: Record<string, any>
  ): Promise<{ filePath: string; filename: string }> {
    this.ensureExportsDir();

    const filename = this.generateFilename(reportType, "xlsx");
    const filePath = path.join(this.EXPORTS_DIR, filename);

    try {
      // Create workbook
      const workbook = XLSX.utils.book_new();

      // Sheet 1: Data
      const dataSheet = XLSX.utils.json_to_sheet(reportData);

      // Format header row
      const range = XLSX.utils.decode_range(dataSheet["!ref"] || "A1");
      for (let C = range.s.c; C <= range.e.c; ++C) {
        const address = XLSX.utils.encode_cell({ r: 0, c: C });
        if (!dataSheet[address]) continue;
        dataSheet[address].s = {
          font: { bold: true, color: { rgb: "FFFFFF" } },
          fill: { fgColor: { rgb: "4472C4" } },
          alignment: { horizontal: "center", vertical: "center" },
        };
      }

      // Auto-size columns
      const maxWidth = 50;
      const colWidths = Array.from({ length: range.e.c + 1 }).map((_, colIdx) => {
        let max = 10;
        for (let r = 0; r <= range.e.r; ++r) {
          const address = XLSX.utils.encode_cell({ r, c: colIdx });
          if (!dataSheet[address]?.v) continue;
          const cellLength = String(dataSheet[address].v).length;
          max = Math.min(Math.max(max, cellLength + 2), maxWidth);
        }
        return { wch: max };
      });
      dataSheet["!cols"] = colWidths;

      XLSX.utils.book_append_sheet(workbook, dataSheet, "Data");

      // Sheet 2: Metadata
      const metadataSheet = XLSX.utils.json_to_sheet([
        { Field: "Report Type", Value: reportType },
        { Field: "Generated At", Value: new Date().toUTCString() },
        { Field: "Total Records", Value: reportData.length },
        ...Object.entries(filters).map(([key, value]) => ({
          Field: key,
          Value: value,
        })),
      ]);

      XLSX.utils.book_append_sheet(workbook, metadataSheet, "Metadata");

      // Write file
      XLSX.writeFile(workbook, filePath);

      return { filePath, filename };
    } catch (error) {
      throw error;
    }
  }

  /**
   * Export data to CSV format
   */
  static async exportToCsv(
    reportType: string,
    reportData: any[],
    filters: Record<string, any>
  ): Promise<{ filePath: string; filename: string }> {
    this.ensureExportsDir();

    const filename = this.generateFilename(reportType, "csv");
    const filePath = path.join(this.EXPORTS_DIR, filename);

    try {
      // Create CSV header
      const headers = reportData.length > 0 ? Object.keys(reportData[0]) : [];
      const csvContent = [
        // Metadata header
        `Report Type,${reportType}`,
        `Generated At,${new Date().toUTCString()}`,
        `Total Records,${reportData.length}`,
        ...Object.entries(filters).map(([key, value]) => `${key},${value}`),
        "", // Empty line
        // CSV data
        headers.join(","),
        ...reportData.map((row) => headers.map((h) => {
          const value = row[h];
          if (value === null || value === undefined) return "";
          if (typeof value === "string" && value.includes(",")) {
            return `"${value.replace(/"/g, '""')}"`;
          }
          return String(value);
        }).join(",")),
      ];

      fs.writeFileSync(filePath, csvContent.join("\n"), "utf-8");

      return { filePath, filename };
    } catch (error) {
      throw error;
    }
  }

  /**
   * Calculate optimal column widths for PDF table
   */
  private static calculateColumnWidths(headers: string[], data: any[]): number[] {
    const pageWidth = 550; // A4 width minus margins
    const minWidth = 60;

    const widths = headers.map((header) => Math.max(minWidth, header.length * 8));
    const totalWidth = widths.reduce((a, b) => a + b, 0);

    // Distribute remaining space proportionally
    const scale = totalWidth > pageWidth ? pageWidth / totalWidth : 1;
    return widths.map((w) => Math.max(minWidth, w * scale));
  }

  /**
   * Delete old exported files (older than X days)
   */
  static cleanupOldExports(daysOld: number = 30): number {
    this.ensureExportsDir();

    const now = Date.now();
    const cutoffTime = now - daysOld * 24 * 60 * 60 * 1000;

    const files = fs.readdirSync(this.EXPORTS_DIR);
    let deleted = 0;

    files.forEach((file) => {
      const filePath = path.join(this.EXPORTS_DIR, file);
      const stats = fs.statSync(filePath);

      if (stats.mtimeMs < cutoffTime) {
        fs.unlinkSync(filePath);
        deleted++;
      }
    });

    return deleted;
  }

  /**
   * Get file download stream
   */
  static getFileStream(filename: string): fs.ReadStream {
    const filePath = path.join(this.EXPORTS_DIR, filename);
    if (!fs.existsSync(filePath)) {
      throw new Error(`File not found: ${filename}`);
    }
    return fs.createReadStream(filePath);
  }
}
