import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join, resolve } from "path";
import { db } from "@workspace/db";
import { reportExportsTable } from "@workspace/db/schema";
import PDFDocument from "pdfkit";
import * as XLSX from "xlsx";

interface ExportOptions {
  reportType: string;
  format: "pdf" | "xlsx" | "csv";
  title?: string;
  logoUrl?: string;
}

/**
 * ExportService - Handles PDF and Excel export generation
 */
export class ExportService {
  private static readonly EXPORT_DIR = resolve(process.cwd(), "exports", "reports");

  constructor() {
    // Ensure export directory exists
    mkdirSync(ExportService.EXPORT_DIR, { recursive: true });
  }

  /**
   * Export report data to PDF format
   */
  static async exportToPdf(
    reportData: any[],
    options: ExportOptions,
    generatedBy: string
  ): Promise<string> {
    return new Promise((resolve, reject) => {
      try {
        const filename = `${options.reportType}-${Date.now()}.pdf`;
        const filepath = join(ExportService.EXPORT_DIR, filename);

        const doc = new PDFDocument({
          margin: 50,
          bufferPages: true,
        });

        const stream = doc.pipe(writeFileSync(filepath, ""));

        // Header
        doc.fontSize(20).font("Helvetica-Bold").text("SMT Verification System", { align: "center" });
        doc.fontSize(12).font("Helvetica").text(options.title || options.reportType, { align: "center" });
        doc.moveDown(0.5);

        // Metadata
        doc.fontSize(10).text(`Generated: ${new Date().toLocaleString()}`, { align: "right" });
        doc.text(`Generated by: ${generatedBy}`, { align: "right" });
        doc.moveDown();

        // Table headers and data
        if (reportData.length > 0) {
          const headers = Object.keys(reportData[0]);
          const columnWidth = (doc.page.width - 100) / headers.length;

          // Headers
          doc.fontSize(9).font("Helvetica-Bold");
          let x = 50;
          headers.forEach((header) => {
            doc.text(header, x, doc.y, { width: columnWidth, lineBreak: false });
            x += columnWidth;
          });
          doc.moveDown();

          // Data rows
          doc.fontSize(8).font("Helvetica");
          reportData.slice(0, 100).forEach((row) => {
            let x = 50;
            headers.forEach((header) => {
              const value = String(row[header] ?? "");
              doc.text(value.substring(0, 50), x, doc.y, { width: columnWidth, lineBreak: false });
              x += columnWidth;
            });
            doc.moveDown();

            // Check if we need a new page
            if (doc.y > doc.page.height - 100) {
              doc.addPage();
            }
          });

          if (reportData.length > 100) {
            doc.moveDown();
            doc.fontSize(9).text(`... and ${reportData.length - 100} more records`, { align: "center" });
          }
        } else {
          doc.text("No data available for this report", { align: "center" });
        }

        // Footer
        doc.fontSize(8).text(`Total records: ${reportData.length}`, { align: "center" });

        doc.end();
        doc.on("finish", () => resolve(filepath));
        doc.on("error", (err) => reject(err));
      } catch (error) {
        reject(new Error(`Failed to export PDF: ${error instanceof Error ? error.message : String(error)}`));
      }
    });
  }

  /**
   * Export report data to Excel format
   */
  static async exportToExcel(
    reportData: any[],
    options: ExportOptions,
    generatedBy: string
  ): Promise<string> {
    try {
      const filename = `${options.reportType}-${Date.now()}.xlsx`;
      const filepath = join(ExportService.EXPORT_DIR, filename);

      const workbook = XLSX.utils.book_new();

      // Main data sheet
      const worksheet = XLSX.utils.json_to_sheet(reportData);

      // Auto-size columns
      const colWidths = Object.keys(reportData[0] || {}).map((key) => ({
        wch: Math.min(20, Math.max(10, key.length + 2)),
      }));
      worksheet["!cols"] = colWidths;

      XLSX.utils.book_append_sheet(workbook, worksheet, "Report Data");

      // Summary sheet
      const summaryData = [
        ["Report Summary"],
        [],
        ["Report Type", options.reportType],
        ["Title", options.title || options.reportType],
        ["Generated By", generatedBy],
        ["Generated At", new Date().toLocaleString()],
        ["Total Records", reportData.length],
      ];
      const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
      XLSX.utils.book_append_sheet(workbook, summarySheet, "Summary");

      // Write file
      XLSX.writeFile(workbook, filepath);

      return filepath;
    } catch (error) {
      throw new Error(`Failed to export Excel: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  /**
   * Export report data to CSV format
   */
  static async exportToCsv(
    reportData: any[],
    options: ExportOptions,
    generatedBy: string
  ): Promise<string> {
    try {
      const filename = `${options.reportType}-${Date.now()}.csv`;
      const filepath = join(ExportService.EXPORT_DIR, filename);

      if (reportData.length === 0) {
        writeFileSync(filepath, "");
        return filepath;
      }

      // Get all keys from first object
      const headers = Object.keys(reportData[0]);
      const csvContent = [
        headers.join(","),
        ...reportData.map((row) =>
          headers
            .map((header) => {
              const value = row[header];
              // Quote and escape strings
              if (typeof value === "string") {
                return `"${value.replace(/"/g, '""')}"`;
              }
              return value ?? "";
            })
            .join(",")
        ),
      ].join("\n");

      writeFileSync(filepath, csvContent);
      return filepath;
    } catch (error) {
      throw new Error(`Failed to export CSV: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  /**
   * Record export activity in database
   */
  static async recordExport(
    reportId: number,
    userId: string,
    format: "pdf" | "xlsx" | "csv",
    ipAddress?: string,
    userAgent?: string
  ): Promise<void> {
    try {
      await db.insert(reportExportsTable).values({
        reportId,
        userId,
        format,
        ipAddress,
        userAgent,
      });
    } catch (error) {
      console.error("Failed to record export:", error);
      // Don't throw - export should succeed even if recording fails
    }
  }

  /**
   * Get file path for exported report
   */
  static getExportPath(filename: string): string {
    return join(ExportService.EXPORT_DIR, filename);
  }

  /**
   * Delete exported report file
   */
  static deleteExportFile(filepath: string): void {
    try {
      // Security: only allow deleting files in the export directory
      const normalizedPath = resolve(filepath);
      const normalizedExportDir = resolve(ExportService.EXPORT_DIR);

      if (!normalizedPath.startsWith(normalizedExportDir)) {
        throw new Error("Invalid file path");
      }

      const fs = require("fs");
      if (fs.existsSync(normalizedPath)) {
        fs.unlinkSync(normalizedPath);
      }
    } catch (error) {
      console.error("Failed to delete export file:", error);
    }
  }
}
