// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/Login.tsx": () => import("../components/mockups/Login.tsx"),
  "./components/mockups/Reports.tsx": () => import("../components/mockups/Reports.tsx")
};
